import { createHash } from "node:crypto";
import { OperatingModelService, digest as modelDigest, sameRef, snapshotKey, stable, targetKey, type AgentHarness, type ContextEnvelope, type DeliveryRecord, type HarnessEvent, type HarnessTool, type OperatingModelAdoption, type OperatingModelId, type OperatingModelOperation, type OperatingModelProposal, type OperatingModelReview, type OperatingModelRevisionRef, type OperatingModelSnapshot, type OperatingModelStorePort } from "@airic/framework";

export interface FakeHarnessStep { text?: string; call?: { tool: string; input: unknown; requestId: string }; event?: HarnessEvent; result?: unknown }
export class FakeHarness implements AgentHarness {
  readonly delivered: DeliveryRecord[] = []; readonly envelopes: ContextEnvelope[] = []; readonly calls: { workId: string; message: string }[] = []; #scripts: FakeHarnessStep[][] = [];
  enqueue(...steps: FakeHarnessStep[]): this { this.#scripts.push(steps); return this; }
  capabilities() { return { resume: true, interrupt: true, contextHook: true, compactionTrace: true }; }
  async run(input: { workId: string; workInput: unknown; message: string; envelope: ContextEnvelope; tools: readonly HarnessTool[]; refreshContext(): Promise<ContextEnvelope>; signal?: AbortSignal; onDelivered(record: DeliveryRecord): Promise<void>; onEvent(event: HarnessEvent): Promise<void> }): Promise<{ text: string; result?: unknown }> {
    this.envelopes.push(input.envelope); this.calls.push({ workId: input.workId, message: input.message }); const delivery: DeliveryRecord = { envelopeDigest: input.envelope.digest, adapter: { id: "fake", version: "1" }, injectionPoints: ["system-prompt", "tool-registry"], registeredTools: input.tools.map((tool) => tool.name) }; this.delivered.push(delivery); await input.onDelivered(delivery);
    const script = this.#scripts.shift() ?? [{ text: "The simulated agent is ready." }]; let text = ""; let result: unknown;
    for (const step of script) { if (input.signal?.aborted) throw new Error("Harness interrupted"); if (step.event) await input.onEvent(step.event); if (step.call) { const tool = input.tools.find((candidate) => candidate.name === step.call!.tool); if (!tool) throw new Error(`FakeHarness cannot find tool ${step.call.tool}`); result = await tool.invoke(step.call.input, step.call.requestId); await input.onEvent({ type: "tool", payload: { phase: "end", name: step.call.tool, requestId: step.call.requestId, isError: false, result } }); const refreshed = await input.refreshContext(); this.envelopes.push(refreshed); const refreshedDelivery = { ...delivery, envelopeDigest: refreshed.digest }; this.delivered.push(refreshedDelivery); await input.onDelivered(refreshedDelivery); } if (step.text) text += step.text; if (step.result !== undefined) result = step.result; }
    return result === undefined ? { text } : { text, result };
  }
  async interrupt(): Promise<void> {}
}
export class MemoryRuntimeStore {
  readonly events: import("@airic/framework").RuntimeEvent[] = []; readonly objects = new Map<string, Uint8Array>();
  async open(): Promise<void> {} async close(): Promise<void> {} async append(events: readonly import("@airic/framework").RuntimeEvent[]): Promise<void> { this.events.push(...events); } async *replay(): AsyncIterable<import("@airic/framework").RuntimeEvent> { yield* this.events; }
  async putObject(content: Uint8Array): Promise<{ digest: string; size: number }> { const digest = String(this.objects.size).padStart(64, "0"); this.objects.set(digest, content); return { digest, size: content.byteLength }; } async getObject(digest: string): Promise<Uint8Array> { const value = this.objects.get(digest); if (!value) throw new Error("Missing object"); return value; }
}
export class MemoryModuleSource {
  constructor(readonly modules: Record<string, { manifest: unknown }>, readonly definitions: Record<string, { manifest: unknown; documents: Record<string, string> }>) {}
  async listModules(): Promise<readonly string[]> { return Object.keys(this.modules); } async readModuleManifest(id: string): Promise<unknown> { return this.modules[id]?.manifest ?? missing(id); }
}
class MemoryOperatingModelStore implements OperatingModelStorePort {
  #snapshots = new Map<string, OperatingModelSnapshot>(); #active = new Map<string, OperatingModelRevisionRef>(); #proposals = new Map<string, OperatingModelProposal>(); #candidates = new Map<string, OperatingModelSnapshot>(); #reviews = new Map<string, OperatingModelReview>(); #operations = new Map<string, OperatingModelOperation>();
  async bootstrap(snapshot: OperatingModelSnapshot): Promise<OperatingModelRevisionRef> { const key = targetKey(snapshot.target); if (!this.#active.has(key)) { this.#snapshots.set(snapshotKey(snapshot.target, snapshot.ref), snapshot); this.#active.set(key, snapshot.ref); } return this.#active.get(key)!; }
  seed(snapshot: OperatingModelSnapshot): void { this.#snapshots.set(snapshotKey(snapshot.target, snapshot.ref), snapshot); this.#active.set(targetKey(snapshot.target), snapshot.ref); }
  async resolveActive(target: OperatingModelId) { const value = this.#active.get(targetKey(target)); if (!value) throw new Error("OperatingModelNotFound"); return value; } async readRevision(target: OperatingModelId, ref: OperatingModelRevisionRef) { const value = this.#snapshots.get(snapshotKey(target, ref)); if (!value) throw new Error("RevisionNotFound"); return value; } async listAvailableModels() { return [...this.#active.keys()].map((key) => { const [moduleId, workTypeId] = key.split("/"); return { moduleId: moduleId!, workTypeId: workTypeId! }; }); } async listRevisions(target: OperatingModelId) { return [...this.#snapshots.values()].filter((item) => targetKey(item.target) === targetKey(target)).map((item) => item.ref); }
  async putProposal(input: { operationId: string; proposal: OperatingModelProposal; candidate: OperatingModelSnapshot }) { if (this.#operations.has(input.operationId)) return this.#operations.get(input.operationId)!; this.#proposals.set(input.proposal.proposalId, input.proposal); this.#candidates.set(input.proposal.proposalId, input.candidate); this.#snapshots.set(snapshotKey(input.candidate.target, input.candidate.ref), input.candidate); return this.#commit(input.operationId, input.proposal); }
  async getProposal(id: string) { const proposal = this.#proposals.get(id); return proposal && this.#view(proposal); } async getCandidate(id: string) { return this.#candidates.get(id); } async listProposals(target?: OperatingModelId) { return [...this.#proposals.values()].filter((item) => !target || targetKey(item.target) === targetKey(target)).map((item) => this.#view(item)); } async getReview(id: string) { return [...this.#reviews.values()].find((item) => item.proposalId === id); }
  async putReview(input: { operationId: string; review: OperatingModelReview }) { if (this.#operations.has(input.operationId)) return this.#operations.get(input.operationId)!; this.#reviews.set(input.review.reviewId, input.review); return this.#commit(input.operationId, input.review); }
  async adoptCandidate(input: { operationId: string; proposal: OperatingModelProposal; review: OperatingModelReview; expectedActiveRevision: OperatingModelRevisionRef }) { if (this.#operations.has(input.operationId)) return this.#operations.get(input.operationId)!; const active = await this.resolveActive(input.proposal.target); if (!sameRef(active, input.expectedActiveRevision) || !sameRef(active, input.proposal.baseRevision)) return this.#reject(input.operationId, "BaseRevisionConflict", "Active revision changed"); const candidate = this.#candidates.get(input.proposal.proposalId)!; const next = { revisionId: `adopted:${candidate.ref.contentDigest.slice(0, 16)}`, contentDigest: candidate.ref.contentDigest }; this.#snapshots.set(snapshotKey(candidate.target, next), { ...candidate, ref: next, parentRef: active }); this.#active.set(targetKey(candidate.target), next); return this.#commit(input.operationId, { adoptionId: `adoption:${input.operationId}`, proposalId: input.proposal.proposalId, previousActive: active, activeRevision: next, reviewBinding: { reviewId: input.review.reviewId, proposalDigest: input.review.proposalDigest, validationReceiptDigest: input.review.validationReceiptDigest } }); }
  async inspectOperation(id: string) { return this.#operations.get(id); } #commit(operationId: string, result: OperatingModelProposal | OperatingModelReview | OperatingModelAdoption): OperatingModelOperation { const operation: OperatingModelOperation = { operationId, status: "committed", result }; this.#operations.set(operationId, operation); return operation; } #reject(operationId: string, code: string, message: string): OperatingModelOperation { const operation: OperatingModelOperation = { operationId, status: "rejected", error: { code, message } }; this.#operations.set(operationId, operation); return operation; } #view(proposal: OperatingModelProposal): OperatingModelProposal { const review = [...this.#reviews.values()].find((item) => item.proposalId === proposal.proposalId); const adopted = [...this.#operations.values()].some((operation) => operation.status === "committed" && "adoptionId" in operation.result && operation.result.proposalId === proposal.proposalId); const active = this.#active.get(targetKey(proposal.target)); return { ...proposal, status: adopted ? "adopted" : !active || !sameRef(active, proposal.baseRevision) ? "stale" : review?.decision === "rejected" ? "rejected" : review?.decision === "approved" ? "approved" : "open" }; }
}
/** Test-only service with the same runtime and governance boundaries as production. */
export class MemoryOperatingModelRepository extends OperatingModelService {
  readonly #store: MemoryOperatingModelStore; readonly #definitions: Record<string, { manifest: unknown; documents: Record<string, string> }>;
  constructor(definitions: Record<string, { manifest: unknown; documents: Record<string, string> }>) { const store = new MemoryOperatingModelStore(); super(store); this.#store = store; this.#definitions = definitions; for (const [key] of Object.entries(definitions)) this.#seed(key); }
  override async resolveActive(target: OperatingModelId): Promise<OperatingModelRevisionRef> { const active = await this.store.resolveActive(target); if (active.revisionId.startsWith("baseline:")) this.#seed(targetKey(target)); return this.store.resolveActive(target); }
  async replaceActiveForTest(target: OperatingModelId, changes: Record<string, string>): Promise<OperatingModelRevisionRef> { const active = await this.resolveActive(target); const snapshot = await this.readRevision(target, active); const files = snapshot.files.map((file) => changes[file.path] === undefined ? file : { ...file, content: changes[file.path]!, digest: digest(changes[file.path]!) }); const contentDigest = modelDigest(stable(files.map(({ path, content }) => ({ path, content })))); const ref = { revisionId: `test:${contentDigest.slice(0, 16)}`, contentDigest }; this.#store.seed({ ...snapshot, ref, parentRef: active, files }); return ref; }
  #seed(key: string): void { const value = this.#definitions[key]; if (!value) return; const [moduleId, workTypeId] = key.split("/"); const files = [{ path: "work.yml", content: JSON.stringify(value.manifest), digest: digest(JSON.stringify(value.manifest)) }, ...Object.entries(value.documents).map(([path, content]) => ({ path, content, digest: digest(content) }))].sort((left, right) => left.path.localeCompare(right.path)); const contentDigest = modelDigest(stable(files.map(({ path, content }) => ({ path, content })))); this.#store.seed({ target: { moduleId: moduleId!, workTypeId: workTypeId! }, ref: { revisionId: `baseline:${contentDigest.slice(0, 16)}`, contentDigest }, files }); }
}
function digest(value: string): string { return createHash("sha256").update(value).digest("hex"); } function missing(id: string): never { throw new Error(`Missing ${id}`); }
